name       : syntax-highlighting
version    : 5.55.0
release    : 21
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.55/syntax-highlighting-5.55.0.tar.xz : d5fc5cf9f96133fc47d18bc740dc73fcd977dce03fe083d1b61f1c9a7eb58503
license    : MIT
component  : programming
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
