name       : syntax-highlighting
version    : 5.72.0
release    : 38
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/syntax-highlighting-5.72.0.tar.xz : 7faf0f620eec7bc0ab8f0dd72b45113b3fab0f9ec85dc6d2215b86dd34c8258f
homepage   : https://community.kde.org/Frameworks
license    : MIT
component  : programming.library
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
