name       : syntax-highlighting
version    : 5.35.0
release    : 2
source     :
    - https://download.kde.org/stable/frameworks/5.35/syntax-highlighting-5.35.0.tar.xz : 3b91ee081d82f0636722bc326ccee3855a419709b6d9953aaaf62137e25a506e
license    : LGPL-2.1
component  : programming
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
