name       : syntax-highlighting
version    : 5.74.0
release    : 39
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/syntax-highlighting-5.74.0.tar.xz : a29fad2b869df141d0e68c4b61769c20759dc1b31be7a8570e2b717a18a08e9b
homepage   : https://community.kde.org/Frameworks
license    : MIT
component  : programming.library
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
