name       : syntax-highlighting
version    : 5.66.0
release    : 32
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/syntax-highlighting-5.66.0.tar.xz : e572719cb64524c6abc476eeccca56f54cb0d7352fc747af3036dbe817566c25
homepage   : https://community.kde.org/Frameworks
license    : MIT
component  : programming
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
