name       : syntax-highlighting
version    : 5.43.0
release    : 9
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.43/syntax-highlighting-5.43.0.tar.xz : 611e6ddbd34f2410a2618cef32cc87b49757001da351369ac16c2b3ee6cd3d28
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
