name       : syntax-highlighting
version    : 5.67.0
release    : 33
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/syntax-highlighting-5.67.0.tar.xz : 17354132c266733027af784cd4b9002cbde16b09a9cfaff5cdc5096dcadc7777
homepage   : https://community.kde.org/Frameworks
license    : MIT
component  : programming
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
