name       : syntax-highlighting
version    : 5.52.0
release    : 18
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.52/syntax-highlighting-5.52.0.tar.xz : 293817aaf2088496343006aa8059de54b6183018c1f5b92f00a9944365f46137
license    : MIT
component  : programming
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
