name       : syntax-highlighting
version    : 5.70.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.70/syntax-highlighting-5.70.0.tar.xz : 4b0e25e2e0070e52f0e463dc876087dc1613910df644757512c3a0ab313d568a
homepage   : https://community.kde.org/Frameworks
license    : MIT
component  : programming.library
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
