name       : syntax-highlighting
version    : 5.50.0
release    : 16
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.50/syntax-highlighting-5.50.0.tar.xz : a4d58e7b65a35e9ee4b6dae7422c530730a590efa905e49e2456ef87a1433c82
license    : MIT
component  : programming
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
