name       : syntax-highlighting
version    : 5.47.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/syntax-highlighting-5.47.0.tar.xz : 0c6c138605639a67ed33ca6ef843144f95cd1aec7ed836c44e14ee3e362b622f
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
