name       : syntax-highlighting
version    : 5.68.0
release    : 34
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.68/syntax-highlighting-5.68.0.tar.xz : a857c743aa60b21eea7e4b986e8b195882aa2c18358412e767e68d93ce35e134
homepage   : https://community.kde.org/Frameworks
license    : MIT
component  : programming.library
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
