name       : syntax-highlighting
version    : 5.109.0
release    : 69
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.109/syntax-highlighting-5.109.0.tar.xz : 9e637ae8e92dce33ab0f658e30d6aa132fc354304f90ffb099cd27c776d0b5c7
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
