name       : syntax-highlighting
version    : 5.53.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.53/syntax-highlighting-5.53.0.tar.xz : aa31517936a6c19080c2a62519d7eecd4c369a881614f841028b5d82ac0225ab
license    : MIT
component  : programming
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
