name       : syntax-highlighting
version    : 5.40.0
release    : 6
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/syntax-highlighting-5.40.0.tar.xz : 148dd0d3d091ad5ee352cc528f494a375d89d2812ff31b08c735e0929a358075
license    : LGPL-2.1
component  : programming
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
