name       : syntax-highlighting
version    : 5.54.0
release    : 20
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.54/syntax-highlighting-5.54.0.tar.xz : 1496e8a8ea264b21ee5bd89d3c04a6c6ff26ea50c3de222cc3a810f6d6bc5508
license    : MIT
component  : programming
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
