name       : syntax-highlighting
version    : 5.42.0
release    : 8
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/syntax-highlighting-5.42.0.tar.xz : c034d9a43d81fb29af21af419169c15192d0566d2e07d2499c3215044af591c7
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
