name       : syntax-highlighting
version    : 5.32.0
release    : 1
source     :
    - https://download.kde.org/stable/frameworks/5.32/syntax-highlighting-5.32.0.tar.xz : a31f5f66b642ffdb2839c6278428961839b2d13a2ca80561e5eff13a4a3f35b5
license    : LGPL-2.1
component  : programming
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
