name       : syntax-highlighting
version    : 5.75.0
release    : 40
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/syntax-highlighting-5.75.0.tar.xz : c5db1b9a268fa81a1cf72e83c1b3147e4cf4e043da45d917df0165f42ca0d07f
homepage   : https://community.kde.org/Frameworks
license    :
    - LGPL-2.0-or-later
    - MIT
component  : programming.library
optimize   : lto
summary    : Syntax highlighting engine for Kate syntax definitions
description: |
    This is a stand-alone implementation of the Kate syntax highlighting engine. It's meant as a building block for text editors as well as for simple highlighted text rendering (e.g. as HTML), supporting both integration with a custom editor as well as a ready-to-use QSyntaxHighlighter sub-class.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5XmlPatterns)
    - extra-cmake-modules
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
